# Generated by Django 3.2.20 on 2023-07-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.middleware
import drf_system_setting.core.models
import drfexts.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', drfexts.fields.StatusField(choices=[(0, '已删除'), (5, '待提交'), (10, '待生效'), (25, '暂停中'), (50, '已生效'), (75, '待失效'), (100, '已失效')], default=50, help_text='100：已失效，75：待失效，50：有效，25：暂停中，10：待生效，5：待提交，0：删除', verbose_name='状态')),
                ('updated_at', drfexts.fields.UpdatedAtField(auto_now=True, help_text='该记录的最后修改时间', verbose_name='修改时间')),
                ('created_at', drfexts.fields.CreatedAtField(auto_now_add=True, help_text='该记录的创建时间', verbose_name='创建时间')),
                ('sort', drfexts.fields.IntegerField(help_text='排序', null=True, verbose_name='排序')),
                ('code', drfexts.fields.CharField(help_text='编号', max_length=100, unique=True, verbose_name='编号')),
                ('name', drfexts.fields.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('stable', drfexts.fields.BooleanField(default=False, help_text='内置', verbose_name='内置')),
                ('description', drfexts.fields.CharField(blank=True, default='', help_text='描述', max_length=255, verbose_name='描述')),
                ('hidden', drfexts.fields.BooleanField(default=False, help_text='隐藏', verbose_name='隐藏')),
                ('keep_alive', drfexts.fields.BooleanField(default=True, help_text='缓存', verbose_name='缓存')),
                ('is_link', drfexts.fields.BooleanField(default=False, help_text='是否连接', verbose_name='是否连接')),
                ('icon', drfexts.fields.CharField(blank=True, default='', help_text='图标', max_length=50, verbose_name='图标')),
                ('component', drfexts.fields.CharField(blank=True, default='', help_text='组件路径', max_length=100, verbose_name='组件路径')),
                ('path', drfexts.fields.CharField(default='', help_text='路径', max_length=256, verbose_name='路径')),
                ('redirect', drfexts.fields.TextField(default='', help_text='重定向', max_length=256, verbose_name='重定向')),
                ('type', drfexts.fields.SmallIntegerField(choices=[(1, '菜单'), (2, '页面'), (3, '按钮')], default=1, help_text='类型', verbose_name='类型')),
                ('created_by', drfexts.fields.CreatedByField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, help_text='该记录的创建者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', drfexts.fields.VirtualForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='drf_system_setting.menu', verbose_name='父级')),
                ('updated_by', drfexts.fields.UpdatedByField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, help_text='该记录的修改人', null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='menu_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'managed': True,
            },
            bases=(models.Model, drf_system_setting.core.models.TreePathMixin),
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', drfexts.fields.StatusField(choices=[(0, '已删除'), (5, '待提交'), (10, '待生效'), (25, '暂停中'), (50, '已生效'), (75, '待失效'), (100, '已失效')], default=50, help_text='100：已失效，75：待失效，50：有效，25：暂停中，10：待生效，5：待提交，0：删除', verbose_name='状态')),
                ('updated_at', drfexts.fields.UpdatedAtField(auto_now=True, help_text='该记录的最后修改时间', verbose_name='修改时间')),
                ('created_at', drfexts.fields.CreatedAtField(auto_now_add=True, help_text='该记录的创建时间', verbose_name='创建时间')),
                ('sort', drfexts.fields.IntegerField(help_text='排序', null=True, verbose_name='排序')),
                ('name', drfexts.fields.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('stable', drfexts.fields.BooleanField(default=False, help_text='内置', verbose_name='内置')),
                ('description', drfexts.fields.CharField(blank=True, default='', help_text='描述', max_length=255, verbose_name='描述')),
                ('code', drfexts.fields.CharField(help_text='编号', max_length=100, verbose_name='编号')),
                ('type', drfexts.fields.SmallIntegerField(choices=[(1, '整数'), (2, '字符串'), (3, '布尔值')], default=1, help_text='类型', verbose_name='类型')),
                ('created_by', drfexts.fields.CreatedByField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, help_text='该记录的创建者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dict_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', drfexts.fields.VirtualForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='drf_system_setting.dict', verbose_name='父级')),
                ('updated_by', drfexts.fields.UpdatedByField(db_constraint=False, default=django_currentuser.middleware.get_current_authenticated_user, help_text='该记录的修改人', null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='dict_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
                'managed': True,
            },
            bases=(models.Model, drf_system_setting.core.models.TreePathMixin),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_setting_menu_name'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('parent', 'code'), name='unique_setting_menu_code'),
        ),
        migrations.AddConstraint(
            model_name='dict',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_setting_dict_name'),
        ),
        migrations.AddConstraint(
            model_name='dict',
            constraint=models.UniqueConstraint(fields=('parent', 'code'), name='unique_setting_dict_code'),
        ),
    ]
